//! Opcode Types

use serde::{Deserialize, Serialize};

// =============================================================================
// OPCODE
// =============================================================================

/// Opcode
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum Opcode {
    STOP,
    ADD,
    MUL,
    SUB,
    DIV,
    SDIV,
    MOD,
    SMOD,
    ADDMOD,
    MULMOD,
    EXP,
    SIGNEXTEND,
    LT,
    GT,
    SLT,
    SGT,
    EQ,
    ISZERO,
    AND,
    OR,
    XOR,
    NOT,
    BYTE,
    SHL,
    SHR,
    SAR,
    SHA3,
    ADDRESS,
    BALANCE,
    ORIGIN,
    CALLER,
    CALLVALUE,
    CALLDATASIZE,
    CALLDATACOPY,
    CODESIZE,
    CODECOPY,
    GASPRICE,
    EXTCODESIZE,
    EXTCODECOPY,
    RETURNDATASIZE,
    RETURNDATACOPY,
    EXTCODEHASH,
    BLOCKHASH,
    COINBASE,
    TIMESTAMP,
    NUMBER,
    DIFFICULTY,
    GASLIMIT,
    CHAINID,
    BASEFEE,
    POP,
    MLOAD,
    MSTORE,
    MSTORE8,
    SLOAD,
    SSTORE,
    JUMP,
    JUMPI,
    PC,
    MSIZE,
    GAS,
    JUMPDEST,
    PUSH1,
    DUP1,
    DUP2,
    DUP3,
    DUP4,
    DUP5,
    DUP6,
    DUP7,
    DUP8,
    DUP9,
    DUP10,
    DUP11,
    DUP12,
    DUP13,
    DUP14,
    DUP15,
    DUP16,
    SWAP1,
    SWAP2,
    SWAP3,
    SWAP4,
    SWAP5,
    SWAP6,
    SWAP7,
    SWAP8,
    SWAP9,
    SWAP10,
    SWAP11,
    SWAP12,
    SWAP13,
    SWAP14,
    SWAP15,
    SWAP16,
    LOG0,
    LOG1,
    LOG2,
    LOG3,
    LOG4,
    CREATE,
    CALL,
    CALLCODE,
    DELEGATECALL,
    CREATE2,
    STATICCALL,
    REVERT,
    INVALID,
    SELFDESTRUCT,
    MCOPY,
    TLOAD,
    TSTORE,
}

impl Opcode {
    pub fn from_u8(v: u8) -> Option<Self> {
        match v {
            0x00 => Some(Self::STOP),
            0x01 => Some(Self::ADD),
            0x02 => Some(Self::MUL),
            0x03 => Some(Self::SUB),
            0x04 => Some(Self::DIV),
            0x05 => Some(Self::SDIV),
            0x06 => Some(Self::MOD),
            0x07 => Some(Self::SMOD),
            0x08 => Some(Self::ADDMOD),
            0x09 => Some(Self::MULMOD),
            0x0a => Some(Self::EXP),
            0x0b => Some(Self::SIGNEXTEND),
            0x10 => Some(Self::LT),
            0x11 => Some(Self::GT),
            0x12 => Some(Self::SLT),
            0x13 => Some(Self::SGT),
            0x14 => Some(Self::EQ),
            0x15 => Some(Self::ISZERO),
            0x16 => Some(Self::AND),
            0x17 => Some(Self::OR),
            0x18 => Some(Self::XOR),
            0x19 => Some(Self::NOT),
            0x1a => Some(Self::BYTE),
            0x1b => Some(Self::SHL),
            0x1c => Some(Self::SHR),
            0x1d => Some(Self::SAR),
            0x20 => Some(Self::SHA3),
            0x30 => Some(Self::ADDRESS),
            0x31 => Some(Self::BALANCE),
            0x32 => Some(Self::ORIGIN),
            0x33 => Some(Self::CALLER),
            0x34 => Some(Self::CALLVALUE),
            0x35 => Some(Self::CALLDATASIZE),
            0x36 => Some(Self::CALLDATACOPY),
            0x37 => Some(Self::CODESIZE),
            0x38 => Some(Self::CODECOPY),
            0x3a => Some(Self::GASPRICE),
            0x3b => Some(Self::EXTCODESIZE),
            0x3c => Some(Self::EXTCODECOPY),
            0x3d => Some(Self::RETURNDATASIZE),
            0x3e => Some(Self::RETURNDATACOPY),
            0x3f => Some(Self::EXTCODEHASH),
            0x40 => Some(Self::BLOCKHASH),
            0x41 => Some(Self::COINBASE),
            0x42 => Some(Self::TIMESTAMP),
            0x43 => Some(Self::NUMBER),
            0x44 => Some(Self::DIFFICULTY),
            0x45 => Some(Self::GASLIMIT),
            0x46 => Some(Self::CHAINID),
            0x47 => Some(Self::BASEFEE),
            0x50 => Some(Self::POP),
            0x51 => Some(Self::MLOAD),
            0x52 => Some(Self::MSTORE),
            0x53 => Some(Self::MSTORE8),
            0x54 => Some(Self::SLOAD),
            0x55 => Some(Self::SSTORE),
            0x56 => Some(Self::JUMP),
            0x57 => Some(Self::JUMPI),
            0x58 => Some(Self::PC),
            0x59 => Some(Self::MSIZE),
            0x5a => Some(Self::GAS),
            0x5b => Some(Self::JUMPDEST),
            0x5e => Some(Self::MCOPY),
            0x5f => Some(Self::TLOAD),
            0x5c => Some(Self::TSTORE),
            0x60 => Some(Self::PUSH1),
            0x80 => Some(Self::DUP1),
            0x90 => Some(Self::SWAP1),
            0xa0 => Some(Self::LOG0),
            0xf0 => Some(Self::CREATE),
            0xf1 => Some(Self::CALL),
            0xf2 => Some(Self::CALLCODE),
            0xf3 => Some(Self::DELEGATECALL),
            0xf4 => Some(Self::CREATE2),
            0xfa => Some(Self::STATICCALL),
            0xfd => Some(Self::REVERT),
            0xfe => Some(Self::INVALID),
            0xff => Some(Self::SELFDESTRUCT),
            _ => None,
        }
    }
}